# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91f7d96798b8aa601daba1c87b140a2c776045ab6bc25fc95c92bd8b4a102d65809dda28559ccdc0f8893b3ed3bd09b6d822de0937e67ad7debbf31cdc209f0d

test:
  secret_key_base: 6aab8b4c1f6aa4b3b7cb292d41f7a2407f476647c056808ac32311509afc64cf3bf19ef641e494ba8121e32708b3799dad9d524ceeaf2d8d7ae4b54fa62ab03d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
